---
- name: RBAC Setup Tasks
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    user: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"

- name: get token
  uri:
    url: "https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7/v1/token"
    method: POST
    validate_certs: false
    return_content: true
    status_code: 200
    url_username: "0oa96pg3lgnBnhY9w5d7"
    url_password: "dshcfgYYnMWhFGIuLzNFQJPhichIRUHgYz9jjRKZLjTV0s97Jueji_8tIjfzExWH"
    force_basic_auth: true
    headers:
      Content-Type: application/x-www-form-urlencoded
    body_format: form-urlencoded
    body:
      - ["grant_type", "client_credentials"]
      - ["scope", "groups"]
  register: mds_token
  until: mds_token.status == 200
  retries: 10
  delay: 5
  when:
    - oauth_enabled|bool

- name: Grant role System Admin to Additional Schema Registry users/groups
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/{% if 'User' not in item and 'Group' not in item %}User:{% endif %}{{item}}/roles/SystemAdmin"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{(mds_token.content | from_json).access_token}}"
    body_format: json
    body: >
      {
        "clusters": {
          "kafka-cluster": "{{kafka_cluster_id}}",
          "schema-registry-cluster": "{{schema_registry_final_properties['schema.registry.group.id']}}"
        }
      }
    status_code: 204
  register: sr_mds_result
  until: sr_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{schema_registry_additional_system_admins}}"
  when: not ansible_check_mode

- name: Grant Schema Registry user the role SecurityAdmin on the Schema Registry cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{schema_registry_ldap_user}}/roles/SecurityAdmin"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{(mds_token.content | from_json).access_token}}"
    body_format: json
    body: >
      {
        "clusters": {
          "kafka-cluster": "{{kafka_cluster_id}}",
          "schema-registry-cluster": "{{schema_registry_final_properties['schema.registry.group.id']}}"
        }
      }
    status_code: 204
  register: sr_mds_result
  until: sr_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  when: not ansible_check_mode

- name: Grant Schema Registry user ResourceOwner Schema Registry Group and Topic
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{schema_registry_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{(mds_token.content | from_json).access_token}}"
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster": "{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [
          {
            "resourceType":"Group",
            "name": "{{schema_registry_final_properties['schema.registry.group.id']}}",
            "patternType":"LITERAL"
          },
          {
            "resourceType":"Topic",
            "name": "{{schema_registry_final_properties['kafkastore.topic']}}",
            "patternType":"LITERAL"
          },
          {
            "resourceType":"Topic",
            "name": "{{schema_registry_final_properties['confluent.license.topic']}}",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: sr_mds_result
  until: sr_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  when: not ansible_check_mode
