---
- name: Extract ClusterId from meta.properties on KRaft Controller
  slurp:
    src: "{{ kafka_controller_final_properties['log.dirs'] }}/meta.properties"
  delegate_to: "{{ groups.kafka_controller[0] }}"
  register: uuid_broker

# - name: Format Storage Directory
#   shell: "{{ binary_base_path }}/bin/kafka-storage  format -t {{ clusterid }} -c {{ kafka_broker.config_file }} --ignore-formatted"
#   register: format_meta
#   vars:
#     clusterid: "{{ (uuid_broker['content'] | b64decode).partition('cluster.id=')[2].partition('\n')[0] }}"

- name: Format Storage Directory
  shell: "{{ binary_base_path }}/bin/kafka-storage  format -t {{ clusterid }} -c {{ kafka_broker.config_file }} \
          --add-scram 'SCRAM-SHA-512=[name={{ sasl_scram_users_final['admin']['principal'] }},password={{ sasl_scram_users_final['admin']['password'] }}]' --ignore-formatted"
  register: format_meta
  vars:
    clusterid: "{{ (uuid_broker['content'] | b64decode).partition('cluster.id=')[2].partition('\n')[0] }}"
  when:
    - "'SCRAM-SHA-512' in kafka_broker_sasl_enabled_mechanisms"
