---
- name: test
  hosts: localhost
  tasks:
    - name: get token
      uri:
        url: "https://dev-59009577.okta.com/oauth2/aus96p2og3u7Cpwu65d7/v1/token"
        method: POST
        validate_certs: false
        return_content: true
        status_code: 200
        url_username: "0oa96pg3lgnBnhY9w5d7"
        url_password: "dshcfgYYnMWhFGIuLzNFQJPhichIRUHgYz9jjRKZLjTV0s97Jueji_8tIjfzExWH"
        force_basic_auth: true
        headers:
          Content-Type: application/x-www-form-urlencoded
        body_format: form-urlencoded
        body:
          - ["grant_type", "client_credentials"]
          - ["scope", "groups"]
      register: mds_result
      until: mds_result.status == 200
      retries: 10
      delay: 5

    - debug:
        msg: "{{(mds_result.content | from_json).access_token}}"
