---
### Validates that Java 11 is in use.

- name: Verify - kafka_controller
  hosts: kafka_controller
  gather_facts: false
  tasks:
    - name: Check process role
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: process.roles
        expected_value: controller

    - name: Check listener
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listeners
        expected_value: CONTROLLER://:9093

    - name: Check quorum voters
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: controller.quorum.voters
        expected_value: 9991@controller1:9093,9992@controller2:9093,9993@controller3:9093

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - name: Check process role
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: process.roles
        expected_value: broker
      when: kraft_enabled|bool

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Java Version
      shell: java -version
      register: version_output

    - name: Assert Java Version is 11
      assert:
        that:
          - version_output.stderr_lines[0] | regex_search("11\.0\.")
        fail_msg: "Current Java Version is: {{version_output.stderr_lines[0]}}. Verify again"
        quiet: true
