### Validates that 2 new ksql nodes are added properly
### Validates that two KSQL clusters are running
### Validates that ksql3 is added to KSQL cluster
### Validates that ksql4 is added to KSQL cluster
### Validates that Control Center Can connect to each KSQL cluster
---

- name: Verify - kafka_controller
  hosts: kafka_controller
  gather_facts: false
  tasks:
    - name: Check process role
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: process.roles
        expected_value: controller

    - name: Check listener
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listeners
        expected_value: CONTROLLER://:9093

    - name: Check quorum voters
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: controller.quorum.voters
        expected_value: 9991@controller1:9093,9992@controller2:9093,9993@controller3:9093

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - name: Check process role
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: process.roles
        expected_value: broker
      when: kraft_enabled|bool

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - name: Check line multi ksql line
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ksql.ssl.truststore.location
        expected_value: /var/ssl/private/control_center.truststore.jks
    - name: Check line ksql cluster
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ksql.url
        expected_value: https://ksql1:8088,https://ksql2:8088,https://ksql3:8088,https://ksql4:8088
    - name: Check line connect cluster2
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.connect.connect-cluster1.cluster
        expected_value: http://kafka-connect1:8083
    - name: Check advertised url default
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.ksql.ksql.advertised.url
        expected_value: https://ksql1:8088,https://ksql2:8088,https://ksql3:8088,https://ksql4:8088
