---
# - name: Get ClusterId
#   shell: "{{ binary_base_path }}/bin/kafka-storage random-uuid"
#   environment:
#     KAFKA_OPTS: "-Xlog:all=error -XX:+IgnoreUnrecognizedVMOptions"
#   register: uuid_key
#   run_once: true

- name: Extract ClusterId from meta.properties on KRaft Controller
  slurp:
    src: "/var/lib/kafka/data/meta.properties"
  delegate_to: ec2-54-245-27-229.us-west-2.compute.amazonaws.com
  register: uuid_key

- name: Format Data Directory
  shell: "{{ binary_base_path }}/bin/kafka-storage  format -t {{ clusterid }} -c {{ kafka_controller.config_file }}  --ignore-formatted"
  register: format_meta
  vars:
    clusterid: "{{ (uuid_key['content'] | b64decode).partition('cluster.id=')[2].partition('\n')[0] }}"
