---
skip_properties:
  - num.partitions
  - listener.security.protocol.map
  - sasl.mechanism.inter.broker.protocol
  - group.initial.rebalance.delay.ms
  - confluent.ansible.managed
  - confluent.support.customer.id
  - num.network.threads
  - confluent.support.metrics.enable
  - log.retention.check.interval.ms
  - log.retention.hours
  - log.segment.bytes
  - metric.reporters
  - num.io.threads
  - socket.receive.buffer.bytes
  - socket.request.max.bytes
  - socket.send.buffer.bytes
  - confluent.security.event.logger.exporter.kafka.topic.replicas
  - num.recovery.threads.per.data.dir
  - offsets.topic.replication.factor
  - transaction.state.log.min.isr
  - transaction.state.log.replication.factor
  - sasl.enabled.mechanisms
  - confluent.metrics.reporter.topic.replicas
  - confluent.metrics.reporter.sasl.jaas.config
  - confluent.metrics.reporter.sasl.mechanism
  - confluent.metrics.reporter.security.protocol
  - security.providers
  - ssl.keymanager.algorithm
  - ssl.trustmanager.algorithm
  - ssl.keystore.type
  - ssl.truststore.type
  - confluent.ssl.truststore.location
  - confluent.ssl.truststore.password
  - confluent.ssl.keystore.location
  - confluent.ssl.keystore.password
  - confluent.ssl.key.password
  - listener.name.controller.ssl.key.password
  - listener.name.controller.ssl.keystore.location
  - listener.name.controller.ssl.keystore.password
  - listener.name.controller.ssl.truststore.location
  - listener.name.controller.ssl.truststore.password
  - confluent.ssl.keymanager.algorithm
  - confluent.ssl.trustmanager.algorithm
  - confluent.ssl.keystore.type
  - confluent.ssl.truststore.type
  - confluent.metrics.reporter.ssl.truststore.location
  - confluent.metrics.reporter.ssl.truststore.password
  - confluent.metrics.reporter.ssl.key.password
  - confluent.metrics.reporter.ssl.keystore.location
  - confluent.metrics.reporter.ssl.keystore.password
  - confluent.authorizer.access.rule.providers
  - confluent.metadata.server.ssl.keymanager.algorithm
  - confluent.metadata.server.ssl.trustmanager.algorithm
  - confluent.metadata.server.ssl.keystore.type
  - confluent.metadata.server.ssl.truststore.type
  - confluent.metadata.server.ssl.keystore.location
  - confluent.metadata.server.ssl.keystore.password
  - confluent.metadata.server.ssl.key.password
  - confluent.metadata.server.ssl.truststore.location
  - confluent.metadata.server.ssl.truststore.password
  - confluent.telemetry.enabled
  - confluent.telemetry.api.key
  - confluent.telemetry.api.secret
  - confluent.telemetry.proxy.url
  - confluent.telemetry.proxy.username
  - confluent.telemetry.proxy.password
  - confluent.security.event.logger.exporter.kafka.security.protocol
  - confluent.security.event.logger.exporter.kafka.ssl.key.password
  - confluent.security.event.logger.exporter.kafka.ssl.keystore.location
  - confluent.security.event.logger.exporter.kafka.ssl.keystore.password
  - confluent.security.event.logger.exporter.kafka.ssl.truststore.location
  - confluent.security.event.logger.exporter.kafka.ssl.truststore.password
  - confluent.security.event.logger.exporter.kafka.topic.create
  - confluent.metrics.reporter.sasl.kerberos.service.name
  - listener.name.controller.sasl.kerberos.service.name
  - sasl.kerberos.service.name
  - confluent.telemetry.exporter._local.producer.bootstrap.servers
  - confluent.security.event.router.config
  - confluent.security.event.logger.enable
  - confluent.security.event.logger.exporter.kafka.sasl.jaas.config
  - confluent.security.event.logger.exporter.kafka.sasl.login.callback.handler.class
  - confluent.security.event.logger.exporter.kafka.sasl.mechanism
  - confluent.security.event.logger.exporter.kafka.ssl.client.auth
