---
### Validates that Keystore is present.
### Validates that FIPS is in use in OpenSSL.

- name: Verify - kafka_controller
  hosts: kafka_controller
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/controller/server.properties
        property: listener.name.controller.ssl.keystore.location
        expected_value: /var/ssl/private/kafka_controller.keystore.bcfks

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listener.name.internal.ssl.keystore.location
        expected_value: /var/ssl/private/kafka_broker.keystore.bcfks

    - name: Test TLS version used in certificate
      shell: openssl s_client -connect {{inventory_hostname}}:9091 </dev/null 2>/dev/null  | grep 'Protocol  :' | sed 's/^.*:\ //'
      register: tls_version

    - fail:
        msg: "TLS version is {{tls_version}}, it should be >=1.2"
      when: tls_version is version('TLSv1.2', '<')

    - name: Check FIPS in OpenSSL
      shell: openssl md5 <<< "123"
      register: openssl_out
      failed_when: openssl_out.rc == 0

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/schema_registry.keystore.jks

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/kafka_rest.keystore.jks

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: ssl.truststore.location
        expected_value: /var/ssl/private/kafka_connect.truststore.jks

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/ksql.keystore.jks

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.streams.ssl.truststore.location
        expected_value: /var/ssl/private/control_center.truststore.jks
