---
- name: Kafka Controller Status Finding
  hosts: kafka_controller
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: variables

    - name: Populate service facts
      service_facts:

    - name: Determine Installation Pattern - Parallel or Serial
      set_fact:
        install_pattern: "{{ 'parallel' if service_state != 'running' or kafka_broker_deployment_strategy == 'parallel' else 'serial' }}"
        # delegate_to: kafka_controller
      vars:
        service_state: "{{ ansible_facts.services[kafka_broker_service_name + '.service'].state | default('unknown') }}"

- name: Kafka Controller Parallel Provisioning
  hosts: kafka_controller
  gather_facts: false
  # serial: "{{ '100%' if install_pattern  == 'parallel' else '1' }}"
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_broker
