---
- import_playbook: kafka_controller.yml

- import_playbook: kafka_broker.yml
  vars:
    deployment_strategy: 'serial'

- name: Pause for 2 minutes for migration
  hosts: kafka_controller
  gather_facts: false
  tasks:
    - name: Proceed Prompt
      pause:
        minutes: 2

- name: Migrate Brokers to Kraft
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - name: Remove Zookeeper configs from Broker
      lineinfile:
        path: /etc/kafka/server.properties
        state: absent
        regexp: "{{ item }}*"
      loop:
        - zookeeper
        - inter.broker.protocol.version

    - name: Reconfigure ZK Brokers as KRaft brokers
      lineinfile:
        path: /etc/kafka/server.properties
        line: process.roles=broker

- name: Restart Kafka Broker
  hosts: kafka_broker
  gather_facts: true
  serial: '1'
  tasks:
    - include_role:
        name: kafka_broker
        tasks_from: restart_and_wait.yml
    - include_role:
        name: kafka_broker
        tasks_from: health_check.yml
      tags: health_check

- name: Take Controllers out of migration mode
  hosts: kafka_controller
  gather_facts: false
  tasks:
    - name: Remove Zookeeper configs from Controller
      lineinfile:
        path: /etc/controller/server.properties
        state: absent
        regexp: "{{ item }}*"
      loop:
        - zookeeper

- name: Restart Kafka Controller
  hosts: kafka_controller
  gather_facts: true
  serial: '1'
  tasks:
    - include_role:
        name: kafka_controller
        tasks_from: restart_and_wait.yml
    - include_role:
        name: kafka_controller
        tasks_from: health_check.yml
      tags: health_check

- name: Finish Migration
  hosts: kafka_controller
  tasks:
    - debug:
        msg: "Migration from Zookeeper to Kraft has completed, you may shut down your Zookeeper."
